"""Convention Word native et modele editorial intermediaire."""

from .builder import build_editorial_document, build_editorial_document_from_file
from .convention import NATIVE_WORD_CONVENTION, ParagraphRole, ParagraphRoleKind, WordEditorialConvention
from .model import (
    BibliographicReference,
    BibliographicReferenceInline,
    ColumnBreak,
    DiagnosticSeverity,
    DrawingReference,
    EditorialBlock,
    EditorialBuildResult,
    EditorialBibliography,
    EditorialDiagnostic,
    EditorialDocument,
    EditorialFigure,
    EditorialGraphic,
    EditorialInline,
    EditorialList,
    EditorialListItem,
    EditorialTable,
    EditorialTableCell,
    EditorialTableRow,
    EditorialListKind,
    EditorialLink,
    EditorialNote,
    Heading,
    LineBreak,
    NoteReference,
    PageBreak,
    Paragraph,
    ParagraphRendition,
    ProseQuote,
    ProseQuoteParagraph,
    Tab,
    TextMark,
    TextSpan,
    VerseLine,
    VerseQuote,
    VerseStanza,
)
from .serialization import editorial_build_result_to_data, editorial_build_result_to_json

__all__ = [
    "ColumnBreak",
    "BibliographicReference",
    "BibliographicReferenceInline",
    "DiagnosticSeverity",
    "DrawingReference",
    "EditorialBlock",
    "EditorialBuildResult",
    "EditorialBibliography",
    "EditorialDiagnostic",
    "EditorialDocument",
    "EditorialFigure",
    "EditorialGraphic",
    "EditorialInline",
    "EditorialList",
    "EditorialListItem",
    "EditorialTable",
    "EditorialTableCell",
    "EditorialTableRow",
    "EditorialListKind",
    "EditorialLink",
    "EditorialNote",
    "Heading",
    "LineBreak",
    "NATIVE_WORD_CONVENTION",
    "NoteReference",
    "PageBreak",
    "Paragraph",
    "ParagraphRendition",
    "ParagraphRole",
    "ParagraphRoleKind",
    "ProseQuote",
    "ProseQuoteParagraph",
    "Tab",
    "TextMark",
    "TextSpan",
    "VerseLine",
    "VerseQuote",
    "VerseStanza",
    "WordEditorialConvention",
    "build_editorial_document",
    "build_editorial_document_from_file",
    "editorial_build_result_to_data",
    "editorial_build_result_to_json",
]
