"""Inspection en lecture seule des paquets DOCX OOXML."""

from .inspector import inspect_docx_file
from .model import (
    DocxInspection,
    DocxInspectionError,
    InspectionIssue,
    MediaInfo,
    NumberingDefinitionsInfo,
    NumberingInstanceInfo,
    NumberingListKind,
    NumberingLevelInfo,
    NumberingLevelOverrideInfo,
    NumberingResolutionStatus,
    NoteInfo,
    ParagraphNumberingInfo,
    ParagraphInfo,
    RelationshipInfo,
    RunContentKind,
    RunContentInfo,
    RunInfo,
    StyleInfo,
)

__all__ = [
    "DocxInspection",
    "DocxInspectionError",
    "InspectionIssue",
    "MediaInfo",
    "NumberingDefinitionsInfo",
    "NumberingInstanceInfo",
    "NumberingListKind",
    "NumberingLevelInfo",
    "NumberingLevelOverrideInfo",
    "NumberingResolutionStatus",
    "NoteInfo",
    "ParagraphInfo",
    "ParagraphNumberingInfo",
    "RelationshipInfo",
    "RunContentKind",
    "RunContentInfo",
    "RunInfo",
    "StyleInfo",
    "inspect_docx_file",
]
